In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import urllib.request

In [2]:
# look at the data from kaggle, try to scrape missin data
df_kag = pd.read_csv('Data/Team-stats/nba_team_stats_00_to_18.csv')
df_kag.head(10)

# drop the Unnamed: 0 col
df_kag = df_kag.drop(columns='Unnamed: 0')
df_kag.head()

,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,FG%,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,SEASON
0,Atlanta Hawks,82,29,53,0.354,48.4,113.3,41.4,91.8,45.1,...,46.1,25.8,17.0,8.2,5.1,5.5,23.6,22.2,-6.0,2018-19
1,Boston Celtics,82,49,33,0.598,48.2,112.4,42.1,90.5,46.5,...,44.5,26.3,12.8,8.6,5.3,3.9,20.4,19.5,4.4,2018-19
2,Brooklyn Nets,82,42,40,0.512,48.7,112.2,40.3,89.7,44.9,...,46.6,23.8,15.1,6.6,4.1,5.3,21.5,22.0,-0.1,2018-19
3,Charlotte Hornets,82,39,43,0.476,48.4,110.7,40.2,89.8,44.8,...,43.8,23.2,12.2,7.2,4.9,6.0,18.9,20.6,-1.1,2018-19
4,Chicago Bulls,82,22,60,0.268,48.5,104.9,39.8,87.9,45.3,...,42.9,21.9,14.1,7.4,4.3,5.8,20.3,18.7,-8.4,2018-19

In [3]:
# We want to grab additional data from stats.nba.com for 19-20 and 20-21 season
# Doing the URL request/soup approach didn't get the table data, so I copied the html from the website into an html file
# url_19_20 = "https://www.nba.com/stats/teams/traditional/?PerMode=Totals&sort=TEAM_NAME&dir=-1&Season=2019-20&SeasonType=Regular%20Season"
# url_20_21 = "https://www.nba.com/stats/teams/traditional/?PerMode=Totals&sort=TEAM_NAME&dir=-1&Season=2020-21&SeasonType=Regular%20Season"

In [4]:
# Here is a function to turn a url address into a beautiful soup object
# url should be a string
# file path should also be a string specifying the path to save the html data
def url_to_soup(url, file_path):
    # here we actually access the website
    with urllib.request.urlopen(url) as response:
        html = response.read()
        html = html.decode('utf-8')

    # save the file
    with open(file_path, 'w') as new_file:
        new_file.write(html)

    # here it's already a local operation
    soup = BeautifulSoup(html, 'html.parser')
    return soup

In [5]:
# soup_19_20 = url_to_soup(url_19_20, 'Data/nba-stats-19-to-20-html')
# soup_20_21 = url_to_soup(url_20_21, 'Data/nba-stats-20-to-21-html')
# Looks like the html code doesn't contain the data table

In [6]:
# use pandas to read the 19-20-html table
with open('Data/html/19-20-table.html') as file:
    stat_soup = BeautifulSoup(file, 'html.parser')
stat_table_19_20 = pd.read_html(str(stat_soup))[0]

# delete NaN cols
stat_table_19_20 = stat_table_19_20.dropna(axis='columns')

# Add column to indicate data comes from 2019-2020 season
stat_table_19_20['SEASON'] = '2019-20'

# Looks ready to merge with kaggle dataset!
stat_table_19_20.head()

,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,FG%,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,SEASON
0,Atlanta Hawks,67,20,47,0.299,48.6,111.8,40.6,90.6,44.9,...,43.3,24.0,16.2,7.8,5.1,6.4,23.1,21.0,-8.0,2019-20
1,Boston Celtics,72,48,24,0.667,48.4,113.7,41.3,89.6,46.1,...,46.1,23.0,13.8,8.3,5.6,5.5,21.6,20.7,6.3,2019-20
2,Brooklyn Nets,72,35,37,0.486,48.6,111.8,40.4,90.3,44.8,...,47.9,24.5,15.3,6.4,4.5,5.3,21.0,21.1,-0.6,2019-20
3,Charlotte Hornets,65,23,42,0.354,48.5,102.9,37.3,85.9,43.4,...,42.8,23.8,14.6,6.6,4.1,5.0,18.8,20.6,-6.8,2019-20
4,Chicago Bulls,65,22,43,0.338,48.2,106.8,39.6,88.6,44.7,...,41.9,23.2,15.5,10.0,4.1,5.9,21.8,19.2,-3.1,2019-20

In [7]:
# use pandas to read the 20-21-html table
with open('Data/html/20-21-table.html') as file:
    stat_soup = BeautifulSoup(file, 'html.parser')
stat_table_20_21 = pd.read_html(str(stat_soup))[0]

# delete NaN cols
stat_table_20_21 = stat_table_20_21.dropna(axis='columns')

# Add column to indicate data comes from 2020-2021 season
stat_table_20_21['SEASON'] = '2020-21'

# Looks ready to merge with kaggle dataset!
stat_table_20_21.head()

,Unnamed: 0,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,SEASON
0,1,Utah Jazz,51,38,13,0.745,48.2,116.8,41.3,88.5,...,48.1,23.5,14.0,6.5,5.5,3.9,18.9,19.2,9.4,2020-21
1,2,Phoenix Suns,50,36,14,0.720,48.6,114.6,43.0,87.9,...,43.6,27.1,13.0,6.9,4.3,3.7,19.6,18.2,6.9,2020-21
2,3,Brooklyn Nets,52,36,16,0.692,48.5,119.0,43.4,87.9,...,44.3,26.8,13.7,6.6,5.2,4.6,19.1,18.8,4.8,2020-21
3,4,Philadelphia 76ers,51,35,16,0.686,48.5,114.0,41.5,86.9,...,46.0,23.2,15.1,8.9,6.3,4.6,20.5,21.3,5.0,2020-21
4,5,LA Clippers,52,34,18,0.654,48.0,114.6,41.9,87.0,...,44.5,24.0,12.9,7.2,4.3,3.8,19.3,17.9,6.6,2020-21

In [8]:
# Merge all stat tables together into one
frames = [stat_table_20_21, stat_table_19_20, df_kag]
team_stats = pd.concat(frames)
team_stats.head()

team_stats.to_csv('Data/Team-stats/stats-00-21')

In [9]:
team_stats.describe()

,Unnamed: 0,GP,W,L,WIN%,MIN,PTS,FGM,FGA,FG%,...,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-
count,30.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,...,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000
mean,15.400000,79.185304,39.592652,39.592652,0.499756,48.355272,100.810543,37.576677,82.833706,45.357668,...,31.600160,42.621565,22.100958,14.446326,7.592013,4.902875,4.904633,20.923642,15.829712,-0.006230
std,8.712259,7.620447,12.582981,12.492246,0.149930,0.182022,6.785624,2.338259,3.837249,1.595748,...,2.224205,2.053952,2.121667,1.147795,0.854878,0.800515,0.703928,1.687095,8.804678,4.518904
min,1.000000,49.000000,7.000000,9.000000,0.106000,48.000000,84.200000,32.400000,74.300000,40.800000,...,26.900000,36.900000,17.400000,11.200000,5.500000,2.400000,3.000000,16.600000,0.000000,-13.900000
25%,8.250000,82.000000,30.000000,30.000000,0.390000,48.200000,95.825000,35.925000,80.000000,44.300000,...,29.900000,41.200000,20.600000,13.700000,7.000000,4.300000,4.400000,19.700000,17.950000,-3.100000
50%,15.500000,82.000000,41.000000,39.000000,0.512000,48.400000,99.500000,37.300000,82.400000,45.300000,...,31.300000,42.500000,21.900000,14.500000,7.500000,4.900000,4.900000,20.900000,20.000000,0.100000
75%,22.750000,82.000000,49.000000,49.000000,0.610000,48.500000,104.975000,39.000000,85.600000,46.400000,...,33.100000,44.000000,23.400000,15.100000,8.200000,5.400000,5.400000,22.100000,21.200000,3.375000
max,30.000000,82.000000,73.000000,72.000000,0.890000,49.000000,119.300000,44.500000,94.000000,50.400000,...,42.200000,51.700000,30.400000,18.500000,10.300000,8.200000,6.900000,26.700000,25.700000,11.600000